[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = "57.1.0"
arrow-flight = "57.1.0"
bytes = "1.11.0"
futures-core = "0.3.31"
futures-util = "0.3.31"
tokio = {version="1.48.0",features=["full"]}
tonic = "0.14.2"
